SELECT CURRENT_DATE FROM DUAL
SELECT CURRENT_TIME FROM DUAL
SELECT CURRENT_TIMESTAMP FROM DUAL
CREATE TABLE mes(
 id INT,
 content VARCHAR(30),
 send_time DATETIME)
 INSERT INTO mes VALUES (1,'北京新闻',CURRENT_TIMESTAMP);
 INSERT INTO mes VALUES (2,'上海新闻',NOW());
  INSERT INTO mes VALUES (3,'广州新闻',NOW());
 SELECT * FROM mes;
 SELECT NOW() FROM DUAL
 SELECT id,content,DATE(send_time) FROM mes
 SELECT * FROM mes
 WHERE DATE_ADD(send_time,INTERVAL 10 MINUTE) >= NOW()
 SELECT DATEDIFF('2011-11-11','1990-01-01')/ 365 FROM DUAL
 SELECT DATEDIFF('2000-11-18',NOW())
 SELECT DATEDIFF (DATE_ADD('2000-11-18',INTERVAL 80 YEAR),NOW()) FROM DUAL
 SELECT TIMEDIFF('10:10:11','06:10:10')FROM DUAL
 SELECT YEAR(NOW()) FROM DUAL
 SELECT MONTH(NOW()) FROM DUAL
 SELECT DAY(NOW()) FROM DUAL
 SELECT MONTH('2023-11-23') FROM DUAL
 SELECT UNIX_TIMESTAMP () FROM DUAL
 SELECT FROM_UNIXTIME (1618483484,'%y-%m-%d %h:%i:%s') FROM DUAL
 
 
 
 