CREATE TABLE t24(
	id INT PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(32)NOT NULL DEFAULT '',
	NAME VARCHAR(32)NOT NULL DEFAULT''
	)
INSERT INTO t24 
	VALUES (NULL,'tom@qq.com','tom');
INSERT INTO t24
	(email, NAME) VALUES('hsp@sohu.com','hsp');
SELECT * FROM t24

ALTER TABLE t25 AUTO_INCREMENT = 100
CREATE TABLE t25(
	id INT PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(32) NOT NULL DEFAULT '',
	NAME VARCHAR(32) NOT NULL DEFAULT'')
INSERT INTO t25
	VALUES (NULL,'tom@qq.com','tom')
INSERT INTO t25
	VALUES(666,'hsp@qq.com','hsp')
SELECT * FROM t25