SELECT USER() FROM DUAL
SELECT DATABASE ()
SELECT MD5('hsp') FROM DUAL
CREATE TABLE hsp_user(
id INT,
NAME VARCHAR(32)NOT NULL DEFAULT '',
pwd CHAR(32) NOT NULL DEFAULT '')
INSERT INTO hsp_user VALUES(100,'韩顺平',MD5('hsp'))
SELECT * FROM hsp_user
SELECT * FROM hsp_user
 WHERE NAME = '韩顺平' AND pwd = MD5('hsp')
 
SELECT PASSWORD('hsp') FROM DUAL